### ISSUE TITLE
STL_Toolkit: Overlap geometry are not removed

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/STL_Toolkit#15]
#### Description:

The removeOverlap method in the toolkit is not used anywhere.

#### Expected behaviour:

When the window geometry overlap with wall, the overlap part should be removed when creating the wall STL file.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/STL_Toolkit?csf=1&web=1&e=TLK7zu

**Comment by BingWangUS** [comment]
I have a branch fixing this issue. @vbeardow @FraserGreenroyd let me know if this is something we want to take care now that I will push it for review.

**Comment by vbeardow** [comment]
Hi Bing, I believe the removeOverlaps method was put in as a method to be used manually within grasshopper to give user the option to remove overlaps if they wish/require.

![image](https://user-images.githubusercontent.com/43172233/93499354-c8ad2100-f90a-11ea-9f98-359171529f78.png)

**Comment by BingWangUS** [comment]
Ah ha, that is a good idea. Closing this and will do modification on test procedure now.
