### ISSUE TITLE
STL_Toolkit: Push to STL removeOverlaps error message

### ISSUE THREAD

**Issue by vbeardow** [BHoM/STL_Toolkit#20]
#### Description:
STL testing procedure has identified that push to STL whilst using removeOverlaps component, results in an error message "Couldn't calculate a normal vector of the given curve" when using 4.0 alpha installers. 

STL push still works as normal with STLs created as expected.

No error message thrown when using 3.3 installers, and given there was very minor development to STL toolkit in 4.0 milestone, it is expected that this has been caused by a higher level toolkit, e.g. Geometry Engine. This will require further investigation. 

#### Expected behaviour:
No error message. STL files still created as expected.

#### Test file(s):
[Buildings and Habitats object Model - STL_Toolkit.zip](https://github.com/BHoM/STL_Toolkit/files/5690230/Buildings.and.Habitats.object.Model.-.STL_Toolkit.zip)

**Comment by FraserGreenroyd** [comment]
Unable to replicate using today's code base, as this has been raised in 4.0 and we've just completed 7.0, I suspect it may have been resolved in the intervening time, so I'm closing this as stale for now. If the issue persists then please feel free to reopen 😄
